### PR TITLE
Add more filters to content blocker

### PR DESCRIPTION
**Pull request by Helium314**
I am working on adding more filters which are used in the extension of ABP syntax by AdGuard and uBlockOrigin.

The ones planned for now are the [modifier filters](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#modifier-filters), which don't block, but change the URL or headers.

Currently there is not too much done, the filters can only be read and stored, but are not actually used.

I still need to figure out how to best apply them (can't give an adjusted request back to WebView), so I guess the blocker will need do the changed request and return the reply to WebView (like in https://stackoverflow.com/a/29811280)

### CODE REVIEW

**Comment by Slion** [comment]
@Helium314 Looks like this is still work in progress. I've added the draft label.

**Comment by Helium314** [comment]
This is finally getting somewhere!
In addition to adding more filters used in uBlock and AdGuard lists, I fixed a few bugs / unintended behavior along the way and made the unit tests work again.

What is left:
* maybe re-organize filters that add or remove request / responseheaders (make it more generic)
* add [`badfilter`](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#badfilter) to allow unbreaking bad filter rules
* maybe remove re2j library, as in test it was clearly slower than java.util.regex (needs testing under more "real" conditions)
* checking
  * any problems with doing modified requests via okhttp?
  * does modified `thirdPartyCache` actually work better than the old one?
  * do the new filters work as indended? (some are not so easy to test)
    * $removeparam
    * $csp
    * $removeheader
    * $redirect
    * $important
* performance tests
  * there are new filter options
  * regex filters  might be slow (they were broken and are fixed in this PR)
  * testing is not easy, need to find a way for filters that modify response headers

**Comment by Slion** [comment]
Awesome work going on here. For testing would it help to turn our content blocker engine into it's own module? Maybe even in a separate repository?

**Comment by Helium314** [comment]
Probably it would. I've been thinking about splitting the blocker in a "manager" part for loading and an actual blocker part that does not depend on android-things like `application`.
Problems I have currently:
* android.webkit.MimeTypeMap doesn't work in tests
* creating responses may require `application` for file and resource (string) access
* okhttp is used to do some requests instead of WebView (because headers of request or response are modified), but those requests should not be done when testing

File and resource access should be doable, as both only need to be dummies.
MimeTypeMap can probably be mocked somehow, but needs to provide correct mime types.
The requests will be more work, really not sure how to do it.

**Comment by Helium314** [comment]
Some more filters implemented, tests added and bugs fixed.

Speed tests:
* loading lists (at startup) is unchanged
* decoding lists (after downloading) is ca 20% slower
* blocking checks take about twice as long. Most of the difference actually comes form regex filters, which were not working at all in the old version... so I think there is not much I can do here. With simple lists (no regex filters) there is no clear performance difference (maybe 10%)
* missing: any impact when using OkHttp to do requests? One could easily write filters that basically push all requests through OkHttp...

Except for badfilter, the rest is more or less done

**Comment by Helium314** [comment]
I stumbled upon the problem that `WebResourceRequest` actually doesn't contain the request body (if there is any).
There is https://github.com/KonstantinSchubert/request_data_webviewclient, but according to issues there, it doesn't work for `POST` method.

@Slion 
Do you have any idea how to get the request body in all cases? Or alternatively, let WebView do the request, but allow modifying request and response headers?
Currently the blocker just ignores request types that require a body...

**Comment by Slion** [comment]
@Helium314 Not really, you are the expert there 😁 I would need to take a closer look.

**Comment by Helium314** [comment]
So there are some problems with using okhttp to do the requests (tested with unmodified requests, just done via okhttp instead of letting WebView do it):
1. some methods require a body, which is not included in WebResourceRequest. Maybe the body could be read in other ways, see link above (didn't try yet)
2. on some pages I end up in a loop with the cookie banner
3. on pages that require login, I am logged out when doing requests via okhttp, but logged in again when switching back to WebView.

When doing requests with `isForMainFrame` (as taken from the WebResourceRequest) set to true via WebView, and the others via okhttp, 2. and 3. is fixed in most cases. On NextCloud I end up in an infinite reload cycle after login.
But doing the main frame requests without okhttp means that a lot of filters will not be working properly, such as Content-security-policy header injection ($csp option)

I suspect 3. and maybe 2. might work if *all* requests are done via okhttp, but this requires fixing 1., and might still have other unwanted side effects.
Could it be that okhttp and WebView have some stuff separate? Like cookies, which could explain 3.

For now I would like to finish the PR, with the okhttp problem avoided by not using okhttp and thus not modifying requests.
We could also allow users to enable modifying filters in the content control settings, with a clear warning about the potential side effects.

The problems should then go into a new issue, which should be addressed in a future PR.

**Comment by Helium314** [comment]
It was quite easy to fix 3. with https://stackoverflow.com/a/58982263.
While for 2. this is an improvement, it's not a complete fix. I found https://www.heise.de where Fulguris tries to download some kameleoon-iframe.html when doing requests via okhttp. Excluding main frame requests from okhttp fixes this, but as mentioned above this is not a good solution. I don't know what might be wrong here...

If you want to test it, you can try by adding this (copied to a file) as a local filter list to your filters:
```
[Adblock Plus 2.0]

*$removeheader=whatever
```

**Comment by Helium314** [comment]
@Slion 
As mentioned above, I would like to get this done with the current modify filters (which lead to requests sent via okhttp), and improve them in a later PR.

My plan is making the modify filters optional, with a preference in content control settings. They would be switched off by default and allow enabling modify filters for all requests, or for all non-main-frame requests. When enabling, a warning message will be displayed that informs users about potentially breaking behavior.

**Review by Slion — APPROVED** [review]
Awesome!

**Comment by Slion** [comment]
@Helium314 I'll let you do a squash and merge then when you are ready. Provide a summary of the changes that's smaller than the concatenation of the commits comments.

**Comment by Helium314** [comment]
> Provide a summary of the changes that makes sense and is smaller than the concatenation of the commits comments.

Definitely, right after making the modify filters optional

**Pull request merged**
