### PR TITLE
Domain settings proposal

### PR DESCRIPTION
**Pull request by Helium314**
This is the re-worked version of #194, with one preferences file per domain.
Currently used to store and read per-domain dark mode and desktop mode.

### CODE REVIEW

**Comment by Slion** [comment]
Could be used as a base for #159 
@Helium314 I very much appreciate your effort to contribute. I'll try to review this as soon as I get a chance.

**Comment by Helium314** [comment]
Thanks!
I'm not really experienced with software developement and stuff; I hope this is at least somewhat useful

**Comment by Slion** [comment]
It is extremely useful. So much so that @jamal2362 already integrated it in his Fulguris fork. However it looks like somehow found a bug:
https://github.com/jamal2362/Styx/issues/35

**Comment by Helium314** [comment]
Oops, that was a dumb error caused by editing the file on GitHub instead of pushing the actual code. But quick to fix

**Comment by Helium314** [comment]
I noticed a bit late that this is still open...

I am thinking about changing this to use a database instead of settings. Having one preferences file per page feels quite messy, and there is no simple way to e.g. remove/modify one setting for all pages in case this is necessary due to some update.
Disadvantage of the DB is that I find it annoying to handle, and later addition of a setting requires more effort (at least updating the DB). Probably still worth it.

**Comment by Slion** [comment]
@Helium314 How can I get in touch with you directly? You can reach me by email, available on my GitHub profile.

**Comment by Helium314** [comment]
Oh, I didn't realize that I had set my email to be hidden. Fixed now.

**Comment by Helium314** [comment]
I've again been thinking over this (and would like to finally get it done this year).

For clarification: I've been confusing domain and host here. Actually the settings are applied on a per-host basis, not per-domain.
(see https://www.sistrix.com/ask-sistrix/technical-seo/site-structure/what-is-the-difference-between-a-url-domain-subdomain-hostname-etc)

__Database vs Shared Preferences:__
Database seems more structured, i.e. allows to easily find/modify all entries for a specific host or for a specific setting. With Shared Preferences only one of these is possible in a simple way (with the current approach of storing one preferences file per host, this is per-host).
For the kind of settings we are interested here, I think there is no need for such structured access. The only thing I can think of now would be if a setting needs to be changed, e.g. if we were to switch dark mode from boolean to string for whatever reason. This could be handled by the DB, but also when using one Shared Preferences file per setting (instead of one file per host, like it's done in this PR).

Database is "unwieldy" to use (much code), and slow when accessing. So to avoid DB access slowing the app, it's necessary to cache it in memory. Shared Preferences is doing such caching already without any additional code. With the cache, the DB is more work, but should be same speed in the end (except for slower initial loading, which is maybe 100 ms).

Currently I'm very much in favor of using Shared Preferences because of simplicity and some small gain in loading/startup time.
Reading the table on https://developer.android.com/training/data-storage I feel confirmed (it's always host - setting pairs).

However, I am considering going back to the one-file-per-setting approach in my initial PR, because
* We can more easily change all values of a setting if it ever becomes necessary (thus no real disadvantage to DB)
* We know which Shared Preferences files may exist. This is may be personal preference, but it feels messy. I haven't found any information about whether a large number of files could cause issues with Shared Preferences.
* Potentially less storage is used. With one file per host, we have many files of a few hundred bytes, and each uses up the block size of the file system (4 kB is a common value). But this is likely only relevant for huge amounts of files.

@Slion in https://github.com/Slion/Fulguris/pull/194#issuecomment-850332810 you said you don't like the one-file-per-setting approach. Is this personal preference, or do you think there are further advantages to using one file per host?

Anyway, which settings should be implemented on a per-host basis?
Currently it's only dark mode and desktop mode, but I think disabling javascript and content blocker are also good candidates.

**Comment by Slion** [comment]
> you said you don't like the one-file-per-setting approach. Is this personal preference, or do you think there are further advantages to using one file per host?

Yes, one file per host please, thus you only need to load one file to access one host settings. Also the host settings file size is under control and pretty much known rather than growing to infinity…
Moreover you can thus easily delete one host's settings, just delete that one file.

**Comment by Slion** [comment]
@Helium314 Nice to see you back around here 😁

Though it is not the best time for you to start coding. I still need to merge the styx branch changes back to main so please do not commit anything to main at this stage. I'm hoping I'll get this done this week. If not then most certainly next week. Let's see how it goes.

**Comment by Helium314** [comment]
Alright, then I'll leave the current implementation as it is, and add some further settings.

**Comment by Helium314** [comment]
In the last commit I switched from `url` to `iTargetUrl` because this allows to reload the `domainSettings` only if `iTargetUrl.host` changes.

@Slion I am actually not sure which url is the more suitable. `iTargetUrl` is set i `loadUrl`, `url` basically gets the current url from webView. Should there be a relevant difference?

**Comment by Helium314** [comment]
For java script and image load settings, I would need to add a switch to toggle them somewhere.
The popup menu -> webpage section would be the obvious place, but it is quite large already. Should I still put those settings there?

**Comment by Slion** [comment]
> The popup menu -> webpage section would be the obvious place, but it is quite large already. Should I still put those settings there?

Feel free to use it if it is convenient for testing but eventually domain settings should be accessible from the settings activity and replace the current third party app settings. What you could add in the webpage menu is an option to open the domain settings that launch the settings activity to the correct page.

**Comment by Helium314** [comment]
I ended up going back reading current url every single time domainSettings is accessed.
This is not nice, as it is significantly slower than updating domainSettings when url is changed, but I did not find any reliable way to ensure correct updating. The callbacks I tried are either not 100% reliable, or called too late.
Accessing a single domainSetting only takes some 25-40 µs, but if a url change could be detected reliably, it could be reduced to 1-2 µs.

**Comment by Slion** [comment]
> Accessing a single domainSetting only takes some 25-40 µs, but if a url change could be detected reliably, it could be reduced to 1-2 µs.

I really appreciate you doing such thorough testing when changing core parts of Fulguris. How did you obtain those measurements? I'm confident we will find a satisfying solution eventually.

**Comment by Slion** [comment]
@Helium314 I've merged the Styx branch back to main so it should be easier to move forward now.

**Comment by Helium314** [comment]
> I really appreciate you doing such thorough testing when changing core parts of Fulguris. How did you obtain those measurements? I'm confident we will find a satisfying solution eventually.

I get the results in a rather brutish way. I simply call some functions very often (10000-100000 times) and measure the time by checking `SystemClock.elapsedRealtime()` before and after. If whatever function I call does some caching this is not reliable though.

The few µs difference just feels like a waste of CPU time, especially because calling `webView?.url` is the slow part (20 µs), and the url is likely going to be the same for all calls.
But actually I think the current performance is still very acceptable... even if domainSettings are called 10 times on every url change, it's still less than 1 ms (even on my ancient S4 mini).

**Comment by Helium314** [comment]
Current state:
* dark mode works
* desktop mode is not perfect: sometimes a page can be seen starting in mobile mode before switching to deskop mode again. But this already happens in normal desktop mode without this PR
* load images: no way to set, not tested, but implemented
* block js: looks like it just got implemented in a different way (LightningWebClient, onPageStarted), so what to do here?
* preferences file is not deleted despite [deleteSharedPreference](https://developer.android.com/reference/android/content/Context#deleteSharedPreferences(java.lang.String)) returning true, but that shouldn't bother anyone except people with root access that want to have a look at preferences files

I'm trying to update domainSettings only on init and onPageStarted, as that is when the settings are currently read. Needs some more testing to check whether it is reliable.

**Comment by Slion** [comment]
> block js: looks like it just got implemented in a different way (LightningWebClient, onPageStarted), so what to do here?

Replace the current implementation.

**Comment by Slion** [comment]
We will need a default domain settings page that can be edited like any other domain settings page and will be used to initialiaze newly encountered domain.

**Comment by Slion** [comment]
Quite a few settings from the general settings page can then be moved to domain settings. 
Cookies, load image, show SSL warnings, user agent even. Though we don't need to have all that working on the first delivery. We can migrate settings one by one.

**Comment by Slion** [comment]
In fact it's probably better to initially deliver a first implementation with a very limited set of settings. Thus we can focus and the core mechanics rather than settings specific changes.

I'll let you decide which settings option are to be part of the first delivery, except for the third-party app launch option. This one needs to be part of the initial implementation.

**Comment by Helium314** [comment]
Current state:

Screenshot_20211224-011107_Fulguris
Implemented settings appear to be working, but need some more testing.
If everything is fine, third-party app launch is the only major thing that's missing.

**Comment by Helium314** [comment]
Having it in a single line looks a bit nicer I think:
Screenshot_20211224-120518_Fulguris

For the third party launch option it's basically just moving what happens [here](https://github.com/Slion/Fulguris/blob/06c933abd9d947bc0fa061757cf5efc5b73aedc8/app/src/main/java/acr/browser/lightning/view/LightningWebClient.kt#L461) from preferences to DomainSettings, right?
Plus adding the current setting in the dialog above.

**Comment by Helium314** [comment]
The new menu is a bit slower to access than the current dark and desktop mode toggles, so I hope this is ok. At least toggle should be necessary less often now...
I plan to remove the popup menu items for both, because they should not be needed any more.
Same for the java script settings.

**Comment by Slion** [comment]
Interesting that you did that as a dialog. I thought it should be implemented as a settings preference page. Notably useful for defining defaults.

> For the third party launch option it's basically just moving what happens here from preferences to DomainSettings, right?
Plus adding the current setting in the dialog above.

Something like that yes.

> The new menu is a bit slower to access than the current dark and desktop mode toggles, so I hope this is ok. At least toggle should be necessary less often now...
I plan to remove the popup menu items for both, because they should not be needed any more.
Same for the java script settings

I still think some preferences are useful at the page/tab level, things like force dark or desktop mode for instance. Basically we need to have multiple level of settings. The domain settings define the default when opening a page from a specific domain. But if the user toggles dark mode for a tab it should leave the domain settings unchanged.

**Comment by Slion** [comment]
I like the fact that you have a default option.

**Comment by Slion** [comment]
>  I thought it should be implemented as a settings preference page.

My idea was that domain settings would replace the current Apps settings page and instead of just having one toggle per domain for that one app launch option it provides access to the domain settings page including the launch third party app option.

The page listing all already visited domain should also have an extra domain settings page for the default domain settings to use when we first encounter a new domain.

**Comment by Helium314** [comment]
> Interesting that you did that as a dialog. I thought it should be implemented as a settings preference page. Notably useful for defining defaults.

I thought a dialog feels more "natural" when changing something specifically for the current page, and it lets you see the result for dark and desktop mode changes instantly (also for load images, if the setting is changed from block to load).
But I don't really have an opinion here on how it should be, I'm ok with any way to access the domain settings.

> I still think some preferences are useful at the page/tab level, things like force dark or desktop mode for instance. Basically we need to have multiple level of settings. The domain settings define the default when opening a page from a specific domain. But if the user toggles dark mode for a tab it should leave the domain settings unchanged.
> 
> Force dark mode is both a domain settings option and a tab settings option. All tab settings option override domain settings option. Hope that makes sense.

Personally I don't have any use for such settings on tab level additionally (and I don't see why I could want that).
I think it should then at least be clear that (some) settings available in "Web page" menu are _not_ for page, but actually for tab.

> My idea was that domain settings would replace the current Apps settings page and instead of just having one toggle per domain for that one app launch option, it provides access to the domain settings page including the launch third party app option.
> 
> The page listing all already visited domain should also have an extra domain settings page for the default domain settings to use when we first encounter a new domain.

Ok, I actually have the App settings empty, apparently because I haven't visited any pages that want to open some app. Or maybe this is because I don't have Google services on my phone and thus no play store.

Anyway, I have the impression you have some quite clear ideas how it should be implemented. So maybe it would be simpler if you add that yourself; and I just add the third-party-app to the domain settings.

**Comment by Slion** [comment]
> I thought a dialog feels more "natural" when changing something specifically for the current page

That's the thing it's not specific to just that tab/page.

**Comment by Slion** [comment]
> I think it should then at least be clear that (some) settings available in "Web page" menu are not for page, but actually for tab.

Good point I was even considering changing the name of that menu. Strictly speaking we don't actually have webpage settings, only tab settings.

**Comment by Slion** [comment]
> Personally I don't have any use for such settings on tab level additionally

You may not want to force dark mode on the domain but only turn it on temporary because of the current viewing conditions. Same for desktop mode. The way I see it tab options are easier to toggle from the webpage menu whereas domain settings are more of a case of adjusting them once and let them be.

**Comment by Slion** [comment]
> Ok, I actually have the App settings empty, apparently because I haven't visited any pages that want to open some app. Or maybe this is because I don't have Google services on my phone and thus no play store.

You could test that with websites that have apps. Twitter, Facebook, Reddit, YouTube but also a PDF URL could do that I guess if you have a PDF reader, possibly a bug BTW.

**Comment by Slion** [comment]
> Anyway, I have the impression you have some quite clear ideas how it should be implemented. So maybe it would be simpler if you add that yourself; and I just add the third-party-app to the domain settings.

I agree, I did not mean to push anything on you. What I meant is at the very least we need app launch to be integrated in domain settings before we release it.

Feel free to keep working on that feature as long as you want and let me know when you are happy with it and you want me to take over for the final integration touch which could include third-party app and settings UI. Just be aware that I'm planning to keep the tab specific settings so it would make my life easier if you don't take a destructive approach when doing you implementation.

BTW, I have yet to look at the code. Again just let me know when you want me to take over.

**Comment by Slion** [comment]
>  I have the impression you have some quite clear ideas how it should be implemented. 

Yes, more so than the ad-blocker but again don't let that stop you. I'm also not fixed on what it should be in the end. I may yet change my mind along the way depending of ease of implementation or actual experience when using it.

**Comment by Helium314** [comment]
> You could test that with websites that have apps. Twitter, Facebook, Reddit, YouTube but also a PDF URL could do that I guess if you have a PDF reader, possibly a bug BTW.

Oh... looks like I haven't opened a PDF from browser for about a year. Tested and working.

**Comment by Helium314** [comment]
> You may not want to force dark mode on the domain but only turn it on temporary because of the current viewing conditions. Same for desktop mode. The way I see it tab options are easier to toggle from the webpage menu whereas domain settings are more of a case of adjusting them once and let them be.

Ah I see. While I still don't have use for this, now I understand why someone would want that.

So now the third-party-launch is changed to use domainSettings and is working (in the quick test I did)

What is left:
* make the toggles tab-specific
* add the settings page (instead of the current dialog)
* solve the new merge conflicts
* possibly bug-fixing

**Comment by Helium314** [comment]
> I agree, I did not mean to push anything on you. What I meant is at the very least we need app launch to be integrated in domain settings before we release it.
> 
> Feel free to keep working on that feature as long as you want and let me know when you are happy with it and you want me to take over for the final integration touch which could include third-party app and settings UI. Just be aware that I'm planning to keep the tab specific settings so it would make my life easier if you don't take a destructive approach when doing you implementation.
> 
> BTW, I have yet to look at the code. Again just let me know when you want me to take over.

I think you can start... further settings can be implemented later.

Regarding the tab settings:
I think for the behavior you want, the changes in `toggleDarkMode` and `toggleDesktopMode` should be undone.
`updateDarkMode` and `updateDesktopMode` should not override tab settings, but still work if the user didn't manually change tab settings.

Using the domain settings in the planned settings page should be quite easy: Just create `DomainSettings`, and update the `host` whenever you want to change it.
Or tell me if something is not clear.

**Comment by Slion** [comment]
Thanks, I'll be working on that domain-settings branch from now on. I got it up and running already.

What difference do you make with domain and host? Host for you is the fully qualified domain name? Meaning mostly the domain and subdomain.

**Comment by Helium314** [comment]
> What difference do you make with domain and host? Host for you is the fully qualified domain name? Meaning mostly the domain and subdomain.

The domainSettings always use the fully qualified domain name (as returned by Android's `Uri.getHost()`).

**Pull request merged**
